#!/bin/bash

# Respring if the user has Cydia Substrate installed
if [ -f /Library/MobileSubstrate/MobileSubstrate.dylib ]; then
	declare -a cydia
	cydia=($CYDIA)
	if [[ $1 == remove || $1 == reinstall ]]; then
		if [[ ${CYDIA+@} ]]; then
			eval "echo 'finish:restart' >&${cydia[0]}"
        else
            echo "Please respring your device."
		fi
	fi
fi

exit 0
